name: mytodo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  hive: ^2.2.3
  logger: ^2.5.0
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  overlay_support: ^2.1.0
  google_fonts: ^4.0.1
  intl: ^0.19.0
  dio: ^5.1.1
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  share_plus: ^11.0.0
  flutter_svg: ^1.1.5
  image_picker: ^0.8.4+11
  flutter_screenutil: ^5.7.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_slidable: ^3.1.2
  pinput: ^5.0.1
  local_auth: ^2.3.0
  loading_animation_widget: ^1.2.0+4
  step_progress_indicator: ^1.0.2
  uuid: ^4.5.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  path_provider: ^2.1.5
  carousel_slider: ^5.0.0
  table_calendar: ^3.1.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.4.0

flutter_icons:
  image_path: "assets/pngs/appIcon.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true


flutter:

  
  uses-material-design: true

  assets:
    - assets/jpgs/
    - assets/pngs/
    - assets/svgs/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900